# Generated by Django 5.0.14 on 2026-02-01 18:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('url', models.URLField(max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/', verbose_name='Иконка')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Портал',
                'verbose_name_plural': 'Порталы',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortalAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время проверки')),
                ('is_available', models.BooleanField(verbose_name='Доступен')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='Время ответа (мс)')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP код')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_checks', to='portals.portal', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Проверка доступности',
                'verbose_name_plural': 'Проверки доступности',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['portal', '-timestamp'], name='portals_por_portal__217711_idx')],
            },
        ),
    ]
